### ISSUE TITLE
Substrate kitties tutorial issues

### ISSUE THREAD

**Issue by jakehemmerle** [substrate-developer-hub/substrate-how-to-guides#36]
I'm either missing something really fundamental here or there are some missing instructions for turning the pallet template into an empty kitties pallet.

1. Basic set-up
	- under **Getting started with the node template**
		- Might be worth adding "all instances of `node-template` and `node-template-runtime`   in `/node/Cargo.toml` under features, bin, package, and dependencies should be renamed"; instructions are vague and might suggest not renaming under deps or benchmarks.
  	- under **Creating and integrating pallet_kitties**
		- Should we copy the "most bare-bones version" pallet code into `pallets/kitties/src/lib.rs`? If so, we should state that. So far, it only describes what a bare-bones pallet looks like but then doesn't use it to explain anything.
		- instructing to rename `pallets/template` to `pallet/kitties` breaks everything related to `pallet_template` in `runtime/src/lib.rs`:
			- this includes the import, config impl, TemplateModule reference, benchmarks at the bottom, so instructions handling that should be included
		-  include instructions to rename `pallets/template` to `pallets/kitties` in `/Cargo.toml`.
		-  Fix all references to `pallet_template` in `runtime/src/lib.rs`. There are several, and they don't exist anymore
	    - it says the the `pallets/kitties/Cargo.toml` file should be modified, but it does not say what needs to be modified
			- include instructions of "rename `pallet-template` to `pallet-kitties`"
			- in `runtime/Cargo.toml` include instructions to rename every instance of
	    		- `pallet-template` to `pallet-kitties`
	    		- `../pallets/template` to `../pallets/kitties`
			- in `runtime/src/lib.rs` rename `pallet_template` to `pallet_kitties`
		- `impl pallet_kitties::Config for Runtime {}` implements an empty config for runtime, but it is never included in `construct_runtime!`

**Comment by sacha-l** [comment]
Hi @jakehemmerle - thanks for the issue here! I went over Part I and made some improvements based on your points. 

Please let me know if I'm good to close this issue or if there are still some instructions missing. Cheers!

**Comment by jakehemmerle** [comment]
Sweet! Excited to take a look.

**Comment by jakehemmerle** [comment]
Updates look super clean! Here are some things that need to be added; afterwards, part 1 should compile if followed verbatim.

#### Small typo in "Basic set-up" under step 1:
Should say:
```
path = '../pallets/template'    // <-- 2. Rename to 'path = '../pallets/kitties' '
```
but it says:
```
path = '../pallets/template'    // <-- 2. Rename to 'path = '../pallets/template' '
```
#### `/runtime/src/lib.rs`

the `pallet_template` reference still exists on line 487, needs to be replace with `pallet_kitties`

Also need to replace the 
```
/*--snip--*/
    TemplateModule: pallet_template::{Pallet, Call, Storage, Event<T>}, //<-- Replace this with: 'SubstrateKitties: pallet_kitties::{Module, Call, Config<T>, Storage},'
/*--snip--*/
```
code with 
```
/*--snip--*/
    TemplateModule: pallet_template::{Pallet, Call, Storage, Event<T>}, //<-- Replace this with: 'SubstrateKitties: pallet_kitties::{Pallet, Call, Config<T>, Storage},'
/*--snip--*/
```

#### `node_template_runtime` references in `/node/src/`

all `node_template_runtime` references in `/node/src/`, including chain_spec.rs, command.rs, rpc.rs, service.rs need to be replaced with `kitties_runtime`

#### unused imports in `/pallets/kitties/src/lib.rs`

we can remove the following imports:
```
use frame_support::pallet_prelude::*;
use frame_system::pallet_prelude::*;
```

**Comment by jimmychu0807** [comment]
And then we would also need to modify the `Cargo.toml` that specify these dependencies by name.

**Comment by sacha-l** [comment]
Thanks for the review again @jakehemmerle ! I just made the changes and did a PR [here](https://github.com/substrate-developer-hub/substrate-how-to-guides/pull/39). Feel free to comment directly there and we can merge. 

@jimmychu0807 - thanks for pointing that out. Made the necessary addition in the PR as well.

**Comment by DrW3RK** [comment]
While I was able to troubleshoot multiple issues in the second tutorial  - Part II: Uniqueness, custom types and storage maps, I could not get past this one

`type KittyRandomness: Randomness<H256>;`

This line seems to use legacy version which has 

`impl<T: Trait> Randomness<T::Hash> for Module<T> `

but the current version has

`impl<T: Config> Randomness<T::Hash, T::BlockNumber> for Pallet<T>`

I am also getting this error

StorageMap<_, Twox64Concat, T::Hash, Kitty<T::Hash, T::Balance>, ValueQuery>;
   |                                                                ^^^^^^^ associated type `Balance` not found

Any input is appreciated

**Comment by DrW3RK** [comment]
I did declare that in the specified file. I still get this error

  --> pallets/kitties/src/lib.rs:54:31
   |
54 |         type KittyRandomness: Randomness<H256>;
   |                               ^^^^^^^^^^ ---- supplied 1 type argument
   |                               |
   |                               expected 2 type arguments

I will try your recommendation with pallet config and let you know. Please add this instruction in the tutorial as well.

**Comment by DrW3RK** [comment]
Sorry, unsuccessful again! I think it might be worth for the tutorial authors to start from scratch and follow the instructions as specified and successfully build the code at the end of each module. Also, it would help to have repository with these incremental changes so it is easier to assist newbies stuck at a specific module. I will get back to this tutorial again after it is updated. This is a very good initiative, which requires refinement.

**Comment by sacha-l** [comment]
@DrW3RK - it's helpful to be getting feedback. The tutorial is meant to be a little challenging but not to the point where it's not feasible to complete! 

Linking you to [this folder](https://github.com/substrate-developer-hub/substrate-how-to-guides/blob/main/static/code/kitties-tutorial/03-interacting-functions.rs) which contains the step where you're stuck. The folder needs a little tweaking in terms of naming each file to the corresponding parts of the tutorial but the idea is to provide a guide with "ACTION" items here and there to help complete the parts.

**Comment by DrW3RK** [comment]
Sure. I was digging deep trying to understand the error I was getting with Randomness.

This update happened to Randomness on Mar 10th 2021. Do you think this tutorial instructions still work? If so, what extra implementation needs to be done.
https://github.com/paritytech/substrate/commit/b24c43af1a77168feed445136ea4569f1d132c3a#diff-b78f5c5d2c594cd59a6bde62056c079f1c9ac0094d57c7693ecb861fe53a307f


<img width="1061" alt="Screenshot 2021-07-15 at 12 07 51" src="https://user-images.githubusercontent.com/86818441/125771187-716c316a-06d3-49ac-981d-58fb92700679.png">

**Comment by sacha-l** [comment]
The way Randomness is being implemented in Kitties is kinda admittedly weird. Breaking it down:
- its type for `Config`,  `KittyRandomness` has the `Randomness<H256>` trait to it  - which is why we need to specify imports `use frame_support::traits::Randomness;` and `use sp_core::H256;`.
- then, we pass `RandomnessCollectiveFlip` to configure `KittyRandomness` for our runtime.
- the implementation for `RandomnessCollectiveFlip` that we're using is [here](https://substrate.dev/rustdocs/v3.0.0/src/pallet_randomness_collective_flip/lib.rs.html#102-131) and the reason is that we've specified our `KittyRandomness` type in our pallet

It could have been done all by making a random function inside the pallet. But setting it up by using the `RandomCollectiveFlip` pallet in the runtime is a good way to understand the mechanics of passing in things to our pallet's configuration trait.

**Comment by DrW3RK** [comment]
I may be repeating myself. I still get this error. 

<img width="974" alt="Screenshot 2021-07-15 at 12 58 17" src="https://user-images.githubusercontent.com/86818441/125778521-c8ba97c5-7f5a-4922-9451-684bfab9dc22.png">


You pointed to V.3.0.0 Randomness - https://substrate.dev/rustdocs/v3.0.0/frame_support/traits/trait.Randomness.html
The latest version is here - https://substrate.dev/rustdocs/latest/frame_support/traits/trait.Randomness.html

I am fairly new to Rust (started reading Rust book 10 days ago). Should I be updating cargo.toml file to point to older version of frame-support?

**Comment by jakehemmerle** [comment]
@DrW3RK @sacha-l  the substrate-node-template from the `tutorial/kitties` branch uses a different sources for `frame-support`; your tutorial branch uses registry+https://github.com/rust-lang/crates.io-index which is at least 10 months old, while the new my-substratekitties uses git+https://github.com/paritytech/substrate.git?tag=monthly-2021-07#83808aa815a9fbc528b76cd25ae1dec57e269771. For whatever reason, while both specify version 3.0.0 in `Cargo.lock`, the Randomness API is different between repos, which is a breaking API change.

I also see the `tutorial/kitties` branch also uses FRAME v1 runtime macros. I say we all work together to update the tutorial?

**Comment by jakehemmerle** [comment]
Where you specify
```
fn increment_nonce() -> DispatchResult {
            <Nonce<T>>::try_mutate(|nonce| {
                let next = nonce.checked_add(1).ok_or(Error::<T>::NonceOverflow)?;
                *nonce = next;

                Ok(().into())
            })
        }
```
it should be specified that it must be part of the second `impl<T: Config> Pallet<T> {` implementation

**Comment by jakehemmerle** [comment]
Figured out the versioning stuff; the node template was updated to substrate master here: https://github.com/substrate-developer-hub/substrate-node-template/pull/205

This changed the Cargo.toml for a few files to source its dependencies directly from Substrate github master instead of crates.io, hence the sudden breaking updates.

**Comment by sacha-l** [comment]
Nice catch. This would explain a lot of these issues ... let's work on a PR to fix the tutorial and get it working ?

**Comment by DrW3RK** [comment]
Yeah

**Comment by jakehemmerle** [comment]
First page says:
"Each part should take 30-60 minutes to complete based on your experience" - While I'm far from a rust or substrate expert, I've read through almost the whole rust book, and I'm still far from fitting into this timeframe.

It seems the only way to complete this tutorial as it stands is by referencing lots of existing code (pallets or substrate kitties pallet) to see how things are being done. While this is how we do things in the real world when trying to solve problems or learn something new without documentation, a 'tutorial' by nature should be more fully contained, or at the least, make references to the final code, which isn't the case for the current state of this. This tutorial seems closer to an outline of what you need to do to build a pallet than a tutorial. With that said, I have a few tangible suggestions below

Improvements for part 3:
- helper function `mint()` for error handling and storage write should come before dispatchable
- broken link reference :https://substrate.dev/substrate-how-to-guides/docs/tutorials/Kitties/docs/basics/basic-pallet-integration/
- have helper function implementation first?
- add data model (maybe in part 2?) of how storage entities relate to each other (high level diagram)
    - answers questions like "can kitties exist without an owner?"
- `<SomeStorageMapStruct<T>>::insert(some_key, new_key);` should say `<SomeStorageMapStruct<T>>::insert(key, value);`
- include info on how to check if origin is signed (maybe point to other pallets where this is used eg. democracy) and explain why it is important to do this
- no mentions on what to return or why (DispatchResultsWithPostInfo)
- what weight did you chose to use and why, not just why weights are important (give tldr so people can get on with the tutorial)

What do you say we reopen this issue for visibility?

**Comment by sacha-l** [comment]
See the updated tutorial here: https://docs.substrate.io/tutorials/v3/kitties/pt1
