### ISSUE TITLE
Script to customize Node Template

### ISSUE THREAD

**Issue by sacha-l** [substrate-developer-hub/substrate-how-to-guides#38]
Having a script that sets a template node up in a single command would speed things up for new comers. This would alleviate potential issues as raised in #36. 

It would take away a large chunk of what's in Kitties Part I for example, resulting in a more rewarding experience.

**Comment by sacha-l** [comment]
Working on [this script](https://github.com/sacha-l/substrate-node-template/blob/master/template.toml).

Based off [Kickstart](https://github.com/Keats/kickstart/). What do you think @jimmychu0807 and @NukeManDan ?

**Comment by jimmychu0807** [comment]
Yea. I always think that's good to have a script to rename the default:
1. node name
2. runtime name
3. pallet (`pallet-template`) name

**Comment by sacha-l** [comment]
Completed this. Using it in the Kitties tutorial 🙌🏻 . Run:

```bash
cargo install kickstart
```
and then:

```bash
kickstart https://github.com/sacha-l/kickstart-substrate
```
