### ISSUE TITLE
Integrate kickstart 

### ISSUE THREAD

**Issue by sacha-l** [substrate-developer-hub/substrate-how-to-guides#42]
Use [kickstart](https://github.com/Keats/kickstart) to easily create how-to guides from the CLI. 

E.g:
- Title?
- Goal?
- Use cases?
- Overview?
- Steps?

**Note**: this is a future feature, `kickstart` is a cool tool but still has a few bugs.

**Comment by NukeManDan** [comment]
🤔 so you want to build markdown pages from a CLI tool? What is the advantage over, say, a template md file for new PRs?

**Comment by sacha-l** [comment]
Although this is a "nice to have" option for contributors, it's hard to tell how useful it would be at this point and takes away from focusing on creating new How-to guide content in the list of issues.
