### ISSUE TITLE
Build errors in mint-token pallet

### ISSUE THREAD

**Issue by anaelleltd** [substrate-developer-hub/substrate-how-to-guides#69]
Hi there,

Trying to set up this pallet, but I get the following errors.

![token-error](https://user-images.githubusercontent.com/44770354/130347105-6aa800bd-a83e-42ac-a9d2-e75859113e5e.JPG)

Is something missing from the storage declaration below?

**/// Storage item for balances to accounts mapping.
	#[pallet::storage]
	#[pallet::getter(fn get_balance)]
	pub(super) type BalanceToAccount<T: Config> = StorageMap<
		_, 
		Blake2_128Concat, 
		T::AccountId, 
		T::Balance,
		ValueQuery
		>;**

**Comment by sacha-l** [comment]
Hi @anaelleltd ! Storage declaration looks good. Given that the errors are coming from your pallet events, I'm wondering whether you declared your pallet events properly ? This would look like this: 
 
```rust
	#[pallet::event]
	#[pallet::metadata(T::AccountId = "AccountId")]
	#[pallet::generate_deposit(pub(super) fn deposit_event)]
	pub enum Event<T: Config> {
		/// New token supply was minted.
		MintedNewSupply(T::AccountId),
		/// Tokens were successfully transferred between accounts.
		Transferred(T::AccountId, T::AccountId, T::Balance),
	}
```
In addition, as shown in [step 1](https://substrate.dev/substrate-how-to-guides/docs/basics/mint-token#1-setup-your-pallets-config-trait) make sure you've provided a Balance type to your pallet's configuration trait. 

Feel free to post your code here if these pointers aren't helping &mdash; will be easier for me to understand what you might be missing 😃

**Comment by anaelleltd** [comment]
Thanks for this, Sacha.

I am now getting this error: 
![token-error2](https://user-images.githubusercontent.com/44770354/130392956-d7e1b543-6d2e-4af4-b383-8581a41da0ce.JPG)


Here is my code: 
#![cfg_attr(not(feature = "std"), no_std)]

//! Primitive Token Mint
//! 1. check & store account balances
//! 2. create a token supply
//! 3. pay transfer fees from account balances

#[cfg(test)]
mod mock;

#[cfg(test)]
mod tests;

#[cfg(feature = "runtime-benchmarks")]
mod benchmarking;

#[frame_support::pallet]
pub mod pallet {
	use frame_support::{dispatch::DispatchResultWithPostInfo, pallet_prelude::*};
	use frame_system::pallet_prelude::*;
	use sp_runtime::traits::AtLeast32BitUnsigned;
	use sp_runtime::traits::Saturating;


// Set up config traits: getting necessary types for on-chain actions
#[pallet::config]
pub trait Config: frame_system::Config {
	// Type used to emit events depends on Runtime definition of an event.
	type Event: From<Event<Self>> + IsType<<Self as frame_system::Config>::Event>;

	// Type used to store balances.
	type Balance: Member + Parameter + AtLeast32BitUnsigned + Default + Copy;
}

#[pallet::pallet]
	#[pallet::generate_store(pub(super) trait Store)]
	pub struct Pallet<T>(_);


// Declare storage item StorageMap: tracking balances to accountIDs mapping
#[pallet::storage]
#[pallet::getter(fn get_balance)]

pub(super) type BalanceToAccount<T: Config> = StorageMap<
    _,
    Blake2_128Concat,
    T::AccountId,
    T::Balance,
    ValueQuery
    >;


// Set up events: publishing on-chain actions emitted
#[pallet::event]
#[pallet::metadata(T::AccountId = "AccountId")]
#[pallet::generate_deposit(pub(super) fn deposit_event)]
pub enum Event<T: config> {
	/// Token supply was minted by user.
	MintedNewSupply(T::AccountId),
	/// Token values successfully transferred from and to users' balances.
	Transferred(T::AccountId, T::AccountId, T::Balance),
}

#[pallet::hooks]
	impl<T: Config> Hooks<BlockNumberFor<T>> for Pallet<T> {}


// Create functions: giving capabilities for minting and transfer
#[pallet::call]
	impl<T:Config> Pallet<T> {
		#[pallet::weight(10_000 + T::DbWeight::get().writes(1))]
		pub(super) fn mint(
		    origin: OriginFor<T>,
		    #[pallet::compact] amount: T::Balance
		) -> DispatchResultWithPostInfo {

			// Define mint variable.
		    let sender = ensure_signed(origin)?;

		    // Update storage.
		    <BalanceToAccount<T>>::insert(&sender, amount);

		    // Emit an event.
		    Self::deposit_event(Event::MintedNewSupply(sender));

		    // Return a successful DispatchResultWithPostInfo.
		    Ok(().into())
		}

		#[pallet::weight(1_000)]
		pub(super) fn transfer(
	        origin: OriginFor<T>,
	        to: T::AccountId,
	        #[pallet::compact] amount: T::Balance,
	    ) -> DispatchResultWithPostInfo {

			// Define transfer variables.
	        let sender = ensure_signed(origin)?;
	        let sender_balance = Self::get_balance(&sender);
	        let receiver_balance = Self::get_balance(&to);

	        // Calculate new balances and handle errors.
	    	let update_sender = sender_balance.saturating_sub(amount);
			let update_to = receiver_balance.saturating_add(amount);
	    	
	    	// Write new balances to storage.
	        <BalanceToAccount<T>>::insert(&sender, update_sender);
			<BalanceToAccount<T>>::insert(&sender, update_to);

	        // Emit an event.
	        Self::deposit_event(Event::Transferred(sender, to, amount));

	        // Return a successful DispatchResultWithPostInfo.
	        Ok(().into())
	    }
   }
}

**Comment by anaelleltd** [comment]
Whoops. Classic rookie mistake. 
Thank you for your help on this! 🥇

**Comment by anaelleltd** [comment]
I had another error: 

![token-error3](https://user-images.githubusercontent.com/44770354/131208865-582b1ec2-c62a-4714-ae1b-2d0d810dfa46.JPG)

But found out I needed to add:
`pub use pallet::*;`
in my code.

Is it best practice to use the following instead?
```
use frame_support::{
	decl_error, decl_event, decl_module, decl_storage, dispatch::DispatchResult, ensure,
};
use frame_system::ensure_signed;
```

Thanks.

**Comment by sacha-l** [comment]
Hi @anaelleltd - a couple of things:

- Assuming you're working with the same code referenced at the top of this thread, you're using FRAME v2's attribute macros and not FRAME v1 declarative macros. So you don't need: `decl_error, decl_event, decl_module, decl_storage,`. Refer to [this article about FRAME macros](https://substrate.dev/docs/en/knowledgebase/runtime/macros) to learn more.
- This error is coming from `runtime/src/lib.rs`. It seems you may have not completed [this step](https://substrate.dev/substrate-how-to-guides/docs/basics/mint-token/#4-include-your-pallet-in-your-runtime) to add your pallet to you runtime  

Hope this "un-stucks" you !

**Comment by anaelleltd** [comment]
Pallet has been working alright, no problem.

It's just that I didn't know that the How-To guides were using FRAME v2, hence the confusion about the code.
Cheers. 👍
